name = "last-rite"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

# Custom domains
routes = [
  { pattern = "hoshiyomi.qzz.io", custom_domain = true },
  { pattern = "belajar.ruangguru.com.hoshiyomi.qzz.io", custom_domain = true },
  { pattern = "api24-normal.tiktokv.com.hoshiyomi.qzz.io", custom_domain = true }
]

# Enable logs temporarily for debugging
[observability.logs]
enabled = true
invocation_logs = true
